### ISSUE TITLE
Capability to see the photo associated with a spot, without going into edit on the Notebook.

### ISSUE THREAD

**Issue by sdamaraju** [StraboSpot/StraboSpot2#116]
This seems to be an enhancement request where users want to to be able to see the photo associated with the spot without actually clicking the edit button on the notebook panel.

1. Select any spot that has an image
2. Observe that you see a small image of the photo associated with it on the notebook panel.
3. On click of edit, we can see the full size photo.

Additional information required.
This might need a discussion to understand, how the users want to visualize the photo, is it like a full size photo display right after selecting the spot ?

Screenshots
![image](https://user-images.githubusercontent.com/28953643/88061225-da7d7c80-cb84-11ea-8ff9-1c4fbd8fd81e.png)

**Comment by sdamaraju** [comment]
User comments : "Spot selected with photo. Can I see the photo without going to edit? that would be handy."

**Comment by sdamaraju** [comment]
@nicolasmroberts Can you please elaborate on this requirement.

**Comment by nicolasmroberts** [comment]
@sdamaraju This comment is asking for a small modal to pop up when selecting a spot (rather than the notebook panel). The modal should show the photos/sketches at the spot as well as the first measurement and a button to open the spot in the notebook panel.

**Comment by jessicagood** [comment]
@nicolasmroberts So then have both the small pop-up modal at the Spot on the map AND the notebook open when a Spot is selected on the map? You're sure this is not redundant? Or do you want the notebook to not open when a Spot is selected but wait until the open notebook button in the pop-up modal is pressed?

**Comment by nicolasmroberts** [comment]
@sdamaraju @jessicagood 

Notebook should not open when you tap on a spot (in the current version, it does not open). What should pop up is similar to SS1, a little "speech box" with at least one photo. It should also have the same line of icons that tell the user what kind of data is inside the spot, just like in the spots list (see picture) 
![IMG_C08D2406F4CC-1](https://user-images.githubusercontent.com/35352527/108278941-6e2a2200-7141-11eb-9d56-743eda16ad86.jpeg)
![Screen Shot 2021-02-17 at 5 07 30 PM](https://user-images.githubusercontent.com/35352527/108279714-a3833f80-7142-11eb-85f7-6c8604dbbca3.png)

**Comment by nicolasmroberts** [comment]
Actually, leave out the notebook symbol. You can simply tap on the notebook button to open any selected spot.

**Comment by jessicagood** [comment]
@panamint55

**Comment by jessicagood** [comment]
@panamint55 said not to do this enhancement.
