### ISSUE TITLE
findRootSpot should support more than just points as root Spots

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot2#175]
Create an image basemap in a polygon and then put a point on that image basemap. The function `findRootSpot` finds the root Spot fine but if that root Spot is a polygon it doesn't know how to get the lat and lng for the text display. Test with LineString too. 

https://github.com/StraboSpot/StraboSpot-Mobile/blob/f12cdd59ca5eb25c87a6f9d1fb7056d9b72692b4/src/modules/notebook-panel/notebook-header/NotebookHeader.js#L31

Polygon and LineString are the most important for now but need to also support the less common MultiPoint, MultiLineString and MultiPolygon. And GeometryCollection is another geometry type that will come into play when we do Sed so this needs to be supported as well.

**Comment by jessicagood** [comment]
For now I added a check for the geometry type of Point so the app doesn't crash. Commit ed1d671e22d8e2469783dfd2dadcaf559be3c43f

@nicolasmroberts When there is a Spot on an image basemap in the header in the Notebook panel we show the x, y of that Spot on the image basemap and we also show the lat, lng of the parent of that Spot that is mapped geographically. This works fine if the parent (or we call it the root Spot) is a point. If the root Spot is a polygon or a line then what do we want to show? 
Right now I've fixed it so only the x, y is displayed. 

So the header for a Spot in an image basemap could show:
1. only x, y in the cases where the root Spot is not a Point
2. display 'Polygon' (if the root is a polygon) which is what we display on in the header for the root Spot itself unless it has surface feature info
3. the calculation of the centroid of the polygon

2 is confusing, I would think, and same with 3 since we don't calculate the centroid in the root polygon itself.

What are you thoughts?

**Comment by jessicagood** [comment]
Added check for geometry of type Point for root Spot when assigning lat & lng of root Spot in properties for children Spots with commit 0c82e5922642b7cd1999a29234fdd36a8fb494ed

**Comment by nicolasmroberts** [comment]
@jessicagood For now, I think just saying "polygon" is a fine. A big problem with this approach is that when the database is "flattened" by extracting all the spots, image spots with polygon base spots become completely untethered to any geography. But maybe that is a strabo2.1 problem to sort out.
