### ISSUE TITLE
3D Structures Page

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot2#207]
Get this page working. Accessed in the notebook from the More menu. There is already a placeholder page. See Strabo Spot 1 for functionality. Uses the 4 forms in `assets/forms/three-d-structures`.

**Comment by jessicagood** [comment]
Added with commit c18975533d2b6de5101ed1ecdfcc829d1f632a52

**Comment by jessicagood** [comment]
@nicolasmroberts Are there UI changes you want to make to this? It's pretty much like SS1 now.

**Comment by jessicagood** [comment]
@nicolasmroberts I know @panamint55 wants a compass to show up for 3D Structures. I was going to put this is in but not every 3D Structure has strike/dip or trend/plunge so not sure how to do this yet. And you're probably going to want to change around the UI, adding a modal for quick-entry like the other pages which would incorporate the compass.

**Comment by nicolasmroberts** [comment]
Here is the mockup for 3D structure page. Assets coming in new icons package
![Screen Shot 2021-02-17 at 4 23 20 PM](https://user-images.githubusercontent.com/35352527/108278565-d75d6580-7140-11eb-8d04-e6ab707c9d20.png)
![Screen Shot 2021-02-17 at 4 23 29 PM](https://user-images.githubusercontent.com/35352527/108278569-d9272900-7140-11eb-8099-232060f0bd89.png)
![Screen Shot 2021-02-17 at 4 23 11 PM](https://user-images.githubusercontent.com/35352527/108278571-d9bfbf80-7140-11eb-8ff9-40b7454caa7e.png)

**Comment by nicolasmroberts** [comment]
[StraboIcons_18Feb2021.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/5999188/StraboIcons_18Feb2021.zip)
Icons with 3D structure assets ("FoldAttitude_" and "FoldShape" families). "Close" symbol also updated

**Comment by jessicagood** [comment]
Related #373

**Comment by jessicagood** [comment]
@nicolasmroberts We're missing the image for a dominant fold attitude of 'unknown' and also missing all of the images for dominant hinge shape.

**Comment by jessicagood** [comment]
With commit 8a5e1f99a55c2f7951bd5d2cc8aa660f55b311df the rest of the quick entry modal for Folds was fleshed out, including the Compass.

**Comment by jessicagood** [comment]
@nicolasmroberts Do we have other quick-entry mockups for Tensor or Other? Right now they're just basic forms for the quick-entry.

**Comment by nicolasmroberts** [comment]
@Jessicagood Tensors will stay as it is, because it is a pretty rare one. We will send a mockup for "Other" along with the fold geometry icons for hinge shapes.

**Comment by ellennelson10** [comment]
@jessicagood Here is a mockup for the "Other" tab within 3D structures.

![3DOtherStrabo2 mockup copy](https://user-images.githubusercontent.com/91563766/149986320-97705c49-07da-4281-b954-3147ebacd0f5.png)

The "Primary Boudin Layer Plane", "Primary Neckline", and "Secondary Neckline" buttons bring up the compass tab similar to the fold hinge button. The  "Primary Boudin Layer Plane" is a planar feature (Strike and Dip) and "Primary Neckline"/"Secondary Neckline"  are linear (Trend and Plunge).

**Comment by ellennelson10** [comment]
@jessicagood The new icon package has been added on #385 . It includes the "HingeShape" family of icons.

**Comment by jessicagood** [comment]
Added Hinge Shape icons with commits 181c6ae3ede6bfd5c975ebd75253c0ad31eee1a1 and 7654cc6a12afdd6ba7d3ab3dcd908e114fae90dd

@ellennelson10 Still need icon for Fold Attitude of Unknown

**Comment by jessicagood** [comment]
Icon for Fold Attitude of Unknown added with commit 180ad41117ab9dd9f574ac51a37ce34654e33d84

**Comment by jessicagood** [comment]
Added Other quick entry fields with commit 297211c131c207c038f381ac3d939da879bd1791

**Comment by jessicagood** [comment]
- Fold Notes are where they are to follow @nicolasmroberts mockup (see above). I can easily move them if you want. Let me know.
- When you make a selection on the main page of the Quick Entry Modal the fields shown on the next page are all the fields relevant to the initial field that was selected. So when `mullion` is selected as a `3D Type` all relevant fields are shown on the next page. I can make it so that for `3D Type` only the choices for the `3D Type` itself are shown on the next page. But then you would never see fields relevant to `Lobate-Cuspate` or `other 3D structure`. In order to maintain consistency, for all 3D Types we should either show all relevant fields or show no relevant fields (only the choices for `3D Type` itself). This may be a little confusing but which way do you think it should be?
- Do you want any fields to show up for `Lobate-Cuspate` or 'other 3D structure` in the main page of the Quick Entry Modal? Only `boudinage` was illustrated above and `mullion` is similar.

**Comment by ellennelson10** [comment]
- Yes, please move the field notes to the bottom of the page.
- All 3D types should show no relevant fields until the main page, I included a video attempting to articulate the workflow for that page more clearly. I also did a mockup of the Lobate-Cuspate and other 3D structure fields for the main page which hopefully mitagates the need to show the relevant fields on the 3D type page.

![3DOtherStrabo2 mockup](https://user-images.githubusercontent.com/91563766/154143156-86f6da44-38a7-4348-8584-e89ef0935d08.png)

[RPReplay_Final1644957528.mov.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/8074503/RPReplay_Final1644957528.mov.zip)

**Comment by jessicagood** [comment]
Fixed with 8b88eabd2dbb4f7f4e9246f10a6a91c6efc3020f. We should be able to close this after you check the next release @ellennelson10.

**Comment by ellennelson10** [comment]
@jessicagood I have a couples changes for the 3D structure tab. First, we want to move "tensor" to be part of the "other" section. I attempted to make this change in the Kobo forms, but please let me know if there is something I need to fix on that end. Second, we want to add a "fault" section. It will be redundant to the planar measurement tab, but having it in 3D structures would be useful as well. Again, I added this to the Kobo forms.


![3DStructureMockupMarch2022](https://user-images.githubusercontent.com/91563766/160846486-d5e4e285-2f3d-4f24-9d93-c656528f7221.png)

**Comment by jessicagood** [comment]
I can easily add Fault to 3D Structures but if we remove tensor as a primary type of 3D Structure and move it under Other we will lose the data for where the tensor is already set as a primary 3D Structure. We can have it in both places or see how many people have used tensors or add another section for Tensors (Deprecated). @panamint55 What do you think?

**Comment by panamint55** [comment]
I would say that we see how many are there.  I bet it is none.  If that is the case then we can do the change easily.

What is the reason to remove tensor as a primary structure?

From: Jessica Good ***@***.***>
Reply-To: StraboSpot/StraboSpot-Mobile ***@***.***>
Date: Thursday, March 31, 2022 at 4:09 PM
To: StraboSpot/StraboSpot-Mobile ***@***.***>
Cc: Doug Walker ***@***.***>, Mention ***@***.***>
Subject: Re: [StraboSpot/StraboSpot-Mobile] 3D Structures Page (#207)


I can easily add Fault to 3D Structures but if we remove tensor as a primary type of 3D Structure and move it under Other we will lose the data for where the tensor is already set as a primary 3D Structure. We can have it in both places or see how many people have used tensors or add another section for Tensors (Deprecated). @panamint55<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpanamint55&data=04%7C01%7Cjdwalker%40ku.edu%7C6a52c83a2868489689d508da135acaa3%7C3c176536afe643f5b96636feabbe3c1a%7C0%7C0%7C637843577915558733%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dvTRVVQiIz%2FpF0Bl0mG2EPYYov1Deb2w4N7E0C4KA8o%3D&reserved=0> What do you think?

**Comment by ellennelson10** [comment]
@panamint55 I moved it to "Other" because I don't think the Tensor category is heavily used. It seems reasonable to have it in the "Other" tab instead of at the same level as faults and folds. That being said I didn't realize that it was considered a "primary feature" and wouldn't see any issue with it being [folds][faults][tensors][other].

**Comment by jessicagood** [comment]
@ellennelson10 So should we leave it as is or find out how many people are already using it to see if it's even possible to change?

**Comment by panamint55** [comment]
Ellen will take a look.  It is fine to move tensor under other.  Faults will be added with graphic interface.

**Comment by panamint55** [comment]
Let's check and see if it is used yet.  So go with the 8/23 comment.

**Comment by jessicagood** [comment]
@jasonash says 65 spots use tensors
So @ellennelson10 do think there is a good enough reason to switch the field organization here and lose that data (or go through too much work to try and save the data)?

**Comment by ellennelson10** [comment]
No, it likely isn't worth losing data. So it will be four tabs of "Fold", "Fault", "Tensor", and "Other".

**Comment by jessicagood** [comment]
Added Faults with commit 5a76567a2c1568ebc9615ad5b8bce15db8278d05

Once this comes out in the next release is it good to close @ellennelson10?

**Comment by ellennelson10** [comment]
@jessicagood Yes it will be good to close.
