### ISSUE TITLE
Fabrics Page

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot2#208]
Get this page working. Accessed in the notebook from the More menu. There is already a placeholder page. See Strabo Spot 1 for functionality. Uses the 3 forms in `assets/forms/fabrics`.

**Comment by jessicagood** [comment]
From @nicolasmroberts: View 3D Structures - Fabrics on this page instead of in 3D Structures

**Comment by nicolasmroberts** [comment]
@jessicagood Here is the mockup for Fabrics Page. As you mention above, Fabrics from 3D structures should appear in the notebook page, maybe under a heading of "Fabrics (Depreciated Version)"


![Fabric Mockup_Fault](https://user-images.githubusercontent.com/35352527/108271531-91030900-7136-11eb-8a25-46144b0efbf5.png)
![Fabric Mockup_Igneous](https://user-images.githubusercontent.com/35352527/108271542-952f2680-7136-11eb-8ddd-e2b6dd832ba7.png)
![Fabric Mockup_Metamorphic](https://user-images.githubusercontent.com/35352527/108271546-982a1700-7136-11eb-92b1-f94e699c830e.png)

**Comment by nicolasmroberts** [comment]
Each main button ("planar fabric" for example) pops up a modal with the rest of the kobo form.

**Comment by nicolasmroberts** [comment]
Just like measurements tab, once there is a fabric, it appears in the notebook. Tapping on that brings you to the existing "form input" style page.

**Comment by nicolasmroberts** [comment]
If the user switches from "Fault" to "Igneous" or "Metam." after having input some data without saving, a warning pops up that gives the user an opportunity to save or discard the existing fabric.

**Comment by jessicagood** [comment]
@nicolasmroberts What details of a Fabric do you want to show in the list and how do you want it to look? Label, type, feature type, etc? Right now I just show all of the fields with data but that can get long.

**Comment by jessicagood** [comment]
Added section headers and moved 3D Structures fabrics here with commit 76270b5.
Still need to add modal and format list item view.

**Comment by jessicagood** [comment]
@nicolasmroberts Can you look at the post from Mar 9 above? Still not sure what detail is important to see in the list.

**Comment by nicolasmroberts** [comment]
The list should contain all top headers (I.e., “planar magmatic”) that have been selected for the fabric.

**Comment by jessicagood** [comment]
Do we want the fabric list items alphabetized or just the most recently entered/edited at the top?

**Comment by jessicagood** [comment]
@nicolasmroberts I know this page is to be reworked. Let me know when someone has made any necessary changes to the KoBo forms (without removing or changing the name of current fields, though the labels can be changed) and how the UI is changing.

**Comment by jessicagood** [comment]
Updated with commit d1404e75307b1fe193427bb748a36449dfd05df5 following form updates by @alexanderlusk. @panamint55 decided there was not enough data in the previous form formats to worry too much about the changes to forms. Fields missing in the new format found in the following spreadsheet
[MissingFieldsResponse_Alex.xlsx](https://github.com/StraboSpot/StraboSpot-Mobile/files/7946084/MissingFieldsResponse_Alex.xlsx)
.

**Comment by jessicagood** [comment]
@nicolasmroberts @ellennelson10 You may want to revisit the Quick Entry modals as some of the fields used no longer exist, for example the cohesive, foliated fields for fault rock.

**Comment by jessicagood** [comment]
@alexanderlusk You may want to change some of the field labels where the label is posed as a question. For example, 'Add structural fabric(s)' should probably just be 'Structural Fabrics'. And 'Kinematic indicator(s)?' should just be 'Kinematic Indicators'. There are others too.

**Comment by jessicagood** [comment]
Fabrics forms updated with commit cb46afa so this page may be good to come out of testing mode? @panamint55 @nicolasmroberts @ellennelson10

**Comment by jessicagood** [comment]
@ellennelson10 @panamint55 Any updates on this or do we pull it out of testing mode?

**Comment by panamint55** [comment]
Will review and send a message when done.

**Comment by ellennelson10** [comment]
- I updated the Koboforms, mainly for constancy (e.g., Planar fabrics vs planar fabric). 
- Can we have the "Spatial Configuration" options be under one button on the fault tab similar to how the kinematic indicators or planar fabrics are? (See Photo)
![IMG_50EB96B39469-1](https://user-images.githubusercontent.com/91563766/189721558-85768315-eed4-4e2d-a14b-8e29d4813d32.jpeg)
- @panamint55 Is "Fault" the best descriptor for it's representative tab? It seems like "Structural"  fabrics would be more encompassing?

**Comment by jessicagood** [comment]
First two bullet points fixed with commits 844e28aa18f2621a559348a473a8d4b707ec0548 and 35bcdc052a64c226e64e7b9b0e501f89fb7a5c2b

@panamint55 & @ellennelson10 It is easy to change the tab to say 'Structural' instead of 'Fault.' If that is what you agree on please let me know.

**Comment by panamint55** [comment]
Structural is much better.

**Comment by jessicagood** [comment]
Then to make it make match we'd change the Fault & Shear Zone Fabrics label on the Fabrics page to Structural Fabrics as well? Does that still what you want?

**Comment by jessicagood** [comment]
@panamint55 said yes to previous comment via phone

Fixed with commit c06b0e1072ec21a0ed7d91c367ad78044af1f8ac
