### ISSUE TITLE
Move spots between datasets

### ISSUE THREAD

**Issue by ecp-11** [StraboSpot/StraboSpot2#321]
I have legacy data that i've managed to import from past research using in clino that i'd love to parse out to a better organization once in Strabo, but because spots are stuck in their datasets i can't.

**Describe the solution you'd like**
To be able to move a post from one dataset to another.

**Describe alternatives you've considered**
I've tried copying spots to the active dataset, but this gets clunky and unorganized.

**Comment by NathanNovak** [comment]
Hi @ecp-11 ,

Thanks for the feedback! We will look into that for a future release.  Shouldn't be too difficult so I am sure we can implement this soon.

**Comment by jessicagood** [comment]
This is implemented in the app in the commits above but **disabled** until the server can accept Spots in multiple datasets or at least handle a copy moved to another dataset. @jasonash Datasets for a Spot are now (in the next release) viewable on the metadata page which one gets to by pressing the Spot icon in the notebook.

**Comment by bwwjohnson** [comment]
Any updates on this? I don't seem to be able to do it in StraboSpot v1.19.7

**Comment by jessicagood** [comment]
Added with commit 717e2aba6dc43278b894d5841e9f77b335c60dba.

Added ability to move a single spot to another dataset from the Metadata page - In the Notebook press on the Spot icon in the header.
