### ISSUE TITLE
Android: Test app functionality for Android

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot2#338]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NathanNovak** [comment]
Displaying a pdf in android does not work correctly.  There is a known issue with react-native-webview.  

A work around is to access the help docs in strabospot.org but internet is required.

**Comment by jessicagood** [comment]
Also fix Drag Animation for Android.

**Comment by NathanNovak** [comment]
> Also fix Drag Animation for Android. Freehand drawing buttons.

Currently Mapbox is still having issues with adding draw tools because of Android will not support multiple touch events (https://github.com/nitaliano/react-native-mapbox-gl/issues/1058#issue-298910805). This has been a low priority since then.

**Comment by ellennelson10** [comment]
@NathanNovak @jessicagood  Do we still want this open or should we report Android problems as their own separate issues?

**Comment by NathanNovak** [comment]
We should report Android issues separately but tag the issue as Android.

Nathan Novak

**Comment by NathanNovak** [comment]
Issues need to be in separate issue threads.
