### ISSUE TITLE
The ability to save a template for your notes that appears at each new station (spot)

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#362]
Like measurements template?

**Comment by nicolasmroberts** [comment]
I did not create this, would need to talk to Doug or whoever came up with it to figure out what they were talking about

**Comment by nicolasmroberts** [comment]
@Jessicagood I have more information on this. The idea is to be able to automatically fill any new note with text determined by the user. Frequently users will be inputing the same notes information and would like the headings for that info to already be there.

**Comment by jessicagood** [comment]
Added with commit f04a22110dddece666580ad9247cb4fddb138591

User can have one or more note snippets saved as templates to be applied when the Notes page is opened.
