### ISSUE TITLE
Sed Rock page

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot2#379]
@nicolasmroberts Am I copying any of the SS1 Sed pages for the Sed Rock page? I know this is a priority issue so let me know what you need here.

**Comment by jessicagood** [comment]
Added with commit 99e5e143db1e4977b83a6039adc014564fd45107

Used Sed - Lithologies page from SS1. Changed name to Sed Rocks for SS2.
@nicolasmroberts I need a mock-up for the Quick Entry Modal.

**Comment by panamint55** [comment]
This seems to work.  The entry page you have seems good.

**Comment by jessicagood** [comment]
Quick Entry modal works but is not consistent with the other Quick Entry modals. Depending on the complexity it could be quick to implement if you have a mockup @nicolasmroberts.

**Comment by nicolasmroberts** [comment]
[SedsRocksStrabo2 mockup copy.pdf](https://github.com/StraboSpot/StraboSpot-Mobile/files/7857580/SedsRocksStrabo2.mockup.copy.pdf)

@Jessicagood @NathanNovak here is a mockup of the Seds Rock page.

**Comment by jessicagood** [comment]
Thanks @nicolasmroberts. I also need an icon for this that is different from the Sed Lithologies icon. I'm working on Sed now and using the Sed Lithologies icon for Sed Lithologies.

**Comment by jessicagood** [comment]
@ellennelson10 I also need an icon for the Sed Interval page.

**Comment by jessicagood** [comment]
Added the quick entry modal with commit ac50509f1eff21df24b1c2250e4d5abec4774d82

Still need the icons for this page and the sed interval icons fixed.

**Comment by ellennelson10** [comment]
@jessicagood I added the sed icon to the icon package (see issue #385 ).

**Comment by jessicagood** [comment]
Sed Rocks icon added with commit 180ad41117ab9dd9f574ac51a37ce34654e33d84

**Comment by ellennelson10** [comment]
Whenever I went directly from the Sed Rock page to specifically the Igneous rock page without hitting done or saving, the app would crash. I couldn't get this to happen going from sed rock to other pages.

**Comment by jessicagood** [comment]
@ellennelson10 Could you recreate this in a new project? And tell me the exact steps to reproduce the error. I can't replicate it.

**Comment by nicolasmroberts** [comment]
@jessicagood Here is reproducing that error on my iPad

https://user-images.githubusercontent.com/35352527/154131100-7245e152-88fc-4da3-8c51-ee9f094b1a41.mov

**Comment by jessicagood** [comment]
Thanks. This helped me find and fix the bug. Good catch!

Fixed with commit d88c21052897c414bdab0a8b80b730d7d17e0003

**Comment by panamint55** [comment]
Ellen will review.

**Comment by ellennelson10** [comment]
I updated the kobo forms for the Sed Rock page (added an "other" option to a few categories). Other than that, I think this page looks fine.

**Comment by jessicagood** [comment]
@ellennelson10 The Sed Rock form is used both for the Sed Rocks page and for Lithologies. All of the choices for the field 'Primary Lithology' (which you've changed to 'Sedimentary Rock Type') have a width and pattern for the strat section visualization. But now that 'other' is a choice we do not have a way to display that in the strat section.  Same goes for 'other' that is now a choice for Siliciclastic Type. If you want an 'other' choice how do we visualize them?

**Comment by panamint55** [comment]
I looked at this and I am not sure we need the other for the strat section.  I would not add them as far as I can tell

**Comment by jessicagood** [comment]
So that would remove the 'other' fields from Sed Rocks too since it uses the same form as Primary Lithology.

**Comment by jessicagood** [comment]
@ellennelson10 Per @panamint55 I removed the 'other' options from the KoBo form as that messes up drawing intervals. I archived your form in the KoBo toolbox project list.

If that's it this form may be good to go.
