### ISSUE TITLE
More detail for Geomorphic Feature classification

### ISSUE THREAD

**Issue by andrewkrh** [StraboSpot/StraboSpot2#402]
**Is your feature request related to a problem? Please describe.**
The current options for categorizing geomorphic trace features are not very descriptive

**Describe the solution you'd like**
Here are some proposed dropdown menu items:

Trace Type
-Geomorphic Trace
 
Associated Geomorphic Feature
-Terrace
-Terrace riser
-Moraine
-Dune
-Bedrock ridge
-Debris flow
-Landslide

Geomorphic Trace Type
-Crest
-Base
-Ridge
-gulley
-striation
-shoreline
-stream
-toe
-scarp
 
Landscape Type
-Glacial
-Fluvial
-Marine
-Lacustrine
-Arid
 
Feature Origin
-erosional
-depositional

**Comment by ellennelson10** [comment]
I update the koboforms for trace features and added "other" to the categories.

**Comment by jessicagood** [comment]
Added with commit 846ab50ca46ccc8e4dfd960758a50b3b27683901
