### ISSUE TITLE
Fault Rock Page

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot2#417]
@nicolasmroberts @ellennelson10 

With commit 64b1ba1df9cc95fdac65fa62c6b5117f575e8f2d I've added this page with the form from KoBo Forms titled "Rock Type - Fault and shear zone (11/21)"

Do you have an icon for the new Fault Rock page?
The form is pretty small so I made a basic quick entry modal, like the other rock quick entry modals, but if you want something different let me know.

**Comment by ellennelson10** [comment]
@jessicagood Here is a new icon package with a Fault Rock icon. Yes, just the basic quick entry modal would be awesome.

[30Mar2022.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/8380962/30Mar2022.zip)

**Comment by jessicagood** [comment]
Added icons with commit ef61b5e600e71d951404faac9ed7adc1565250ac
