### ISSUE TITLE
Connection Status and add Interval Icons

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#420]
New icon package including connection status and add interval icons.

I changed the names as suggested to ConnectionStatusButton_online.png and ConnectionStatusButton_offline.png for the regular online/offline icons and then ConnectionStatusButton_connected and ConnectionStatusButton_notconnected for the connectivity icons. 

The names for the add interval buttons are named "AddInterval", "AddInterval_pressed", etc..

[StraboIcons_v23.zip](https://github.com/StraboSpot/StraboSpot-Mobile/files/8390279/StraboIcons_v23.zip)

**Comment by jessicagood** [comment]
Added with commit f01d3ef9d520bafaa8b01002feeb53e7c6e13288

Noticed you have the following duplicates in your package. I removed them so there is no need for a new icon zip but you may want to take them out of your files. Also in the list below I think `SedInterval_pressed.png` is wrong (not the same style as the other files ending in `_pressed.png` but  `SedInterval_pressed_1.png` is correct.

`SedInterval_pressed.png` and `SedInterval_pressed_1.png`
`SedIntervalButton.png` and `SedIntervalButton_1.png`
`SedIntervalButton_pressed.png` and `SedIntervalButton_pressed_1.png`
