### ISSUE TITLE
macrostrat basemap labels are absent

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/StraboSpot2#427]
Using Macrostrat as a basemap (star-Map Layers/default basemaps- Geology from Macrostrat) displays different color geologic map unit polygons but there are no labels shown for the geology polygons from Macrostrat. A label is needed or a way to connect to a link to see Macrostrat polygon data.

v1.20.1

**Comment by jessicagood** [comment]
Added with commits aa2186451c816445e30913ae841a66abc8282326 and b10d2db60d35b85d0498cdee464d9f809f2beb11
