### ISSUE TITLE
StraboSpot2 Lasso data from Stereonet fails to import in new Stereonet Mobile

### ISSUE THREAD

**Issue by srmulcahy** [StraboSpot/StraboSpot2#443]
**Observed Bug**
Uncertain if this is a StraboSpot2 or updated version of Stereonet Mobile (v 4.0.4) bug. Data that are lassoed and copied successfully to the clipboard in StraboSpot2 fail to open in Stereonet Mobile because "the file does not appear to be in a format that the app can open."

**Steps to reproduce the behavior:**
1. In StraboSpot2 Lasso Spots for Stereonet
2. Click on End Draw
3. Success! Data had been copied to the clipboard
4. Open Stereonet Mobile app on iPad
5. Click on Data in top right corner
6. Click the paste symbol in bottom center of screen
7. Messages from Stereonet: "Stereonet Mobile pasted from StraboSpot2" and then "The file does not appear to be one that the ap can open. Sorry!"

**Comment by srmulcahy** [comment]
I also emailed Rick Allmendinger in case the bug is with Stereonet Mobile v 4.0.0

**Comment by NathanNovak** [comment]
We are in the process of updating to fit the new StereoNet v4.x.x.

**Comment by NathanNovak** [comment]
@srmulcahy We have updated the data for v4 of Stereonet.  There is some conversion issues with the time and date that I emailed Rick about.  The changes will be out in a new version soon.

**Comment by NathanNovak** [comment]
I am going to close this issue for now. Feel free to reopen it if you are having anymore issues.
