### ISSUE TITLE
Spots List Crash

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#445]
On one of the iPads running version 1.24.0, every time the user clicks on the "Spots List" in the home menu the app crashes. 
[RPReplay_Final1655214668.mov.zip](https://github.com/StraboSpot/StraboSpot2/files/8909470/RPReplay_Final1655214668.mov.zip)

**Comment by NathanNovak** [comment]
Can you back up the project and send it to us?

Nathan Novak
520-400-5793

**Comment by ellennelson10** [comment]
Yes- we have only seen it on one ipad. I deleted and reinstalled the app but it crashed again later in the day.  The entire project backups are too large to attach but here was the last data.json before I reinstalled the app. Let me know if there are any other files that would be useful.
 
[data.json.zip](https://github.com/StraboSpot/StraboSpot2/files/8915054/data.json.zip)

**Comment by NathanNovak** [comment]
Ok, I'll check it out.

Nathan Novak
520-400-5793

**Comment by NathanNovak** [comment]
@ellennelson10 Should I close this issue?

**Comment by ellennelson10** [comment]
@NathanNovak Yes- close it.
