### ISSUE TITLE
Panning when first loading app will take user to current location å

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#448]
**Describe the bug**
Panning or zooming will reset map to users location after startup.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes/No

1. Load app
2. Pan or zoom

**Expected behavior**
Not to reset location as users location

**Comment by jessicagood** [comment]
Fixed with commit e5512af8f4532646a4992f0f8fa85b488f7be199
