### ISSUE TITLE
Measurements orientation should not have "Associated Liner Feature" in the measurements page

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#449]
In Overview the orientation should say the foliation + the associated linerar/planer feature name

In the Measurements page it does not need to show associated linear/planer feature name.

**Comment by jessicagood** [comment]
Fixed with commit ce5e3d5e5623ed229dc7cc83e575a3bb04109edc.
Also now displaying associated measurement values even when multiple associated measurements.
