### ISSUE TITLE
Lassoing spots with image basemaps does not get image basemap spots

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#450]
Does not get the nested spots on an image basemap.

**Comment by jessicagood** [comment]
The function that determines which spots are included when spots are lassoed is used in 3 places:
- Grabbing the spots to include for Stereonet
- Adding a tag to spots lassoed on the map
- Listing the spots in the map extent (the screen boundary is used as the "lasso")

Should children spots be included in all 3 instances above? Children spots include spots in image basemaps and strat sections and can include a specified number of generations. @panamint55 @ellennelson10

**Comment by panamint55** [comment]
Talked with Ellen.  It should all image basemap spots for Stereonet and all sunspots in images.  Same for tags.  Same for the map extent, probably.  How hard is this to do?

**Comment by jessicagood** [comment]
@panamint55  If they're all the same (if children spots should be included in all 3 situations in the bulleted list above) it is easy and done already. I just need to push it into the code base.

**Comment by panamint55** [comment]
Go for it.
