### ISSUE TITLE
Only one offline map from myMaps appears while offline despite multiple being downloaded

### ISSUE THREAD

**Issue by noahjp-tamu** [StraboSpot/StraboSpot2#452]
**Describe the bug**
When multiple offline maps (from myStrabo maps) are downloaded to an iPad, only one appears when the layers button is clicked.
All maps are visible by going to "Manage Offline Maps"

**To Reproduce**
Yes

1) Download multiple offline maps from custom maps (maps uploaded using StraboSpot myMaps)
2) Go offline
3) click the layers icon - only one map is visible despite multiple being downloaded

**Expected behavior**
All downloaded maps listed and selectable once the layers is clicked

**Comment by NathanNovak** [comment]
What version of Strabo are you using?
