### ISSUE TITLE
Maps uploaded using Strabo My Maps only appear as numbers in the manage offline maps menu

### ISSUE THREAD

**Issue by noahjp-tamu** [StraboSpot/StraboSpot2#453]
**Is your feature request related to a problem? Please describe.**
Yes. When examining downloaded maps in the "Manage Offline Maps" menu, maps downloaded from My Maps show the long string of numbers rather than the name assigned when importing them to the iPad (this makes it impossible to know which map is which while in the field)

**Describe the solution you'd like**
Show the name of the map assigned when adding a map from My Maps to the iPad rather than the string of numbers/letters

**Comment by NathanNovak** [comment]
@noahjp-tamu can you give me a more detailed explanation of the steps you took?  When I download a map from My Maps and then save it for offline use the name appears as it should.
