### ISSUE TITLE
Offline/Custom Maps Not Showing

### ISSUE THREAD

**Issue by dmongovin** [StraboSpot/StraboSpot2#454]
**Describe the bug**
In offline mode, when choosing the 'Map Layers' button on the bottom left of the screen, the downloaded tiles of custom maps are not appearing. When checking to see if offline tiles are downloaded under 'Settings & Preferences -> Manage Offline Maps', the offline map tiles appear. Still, when going into the map layers to choose offline custom map tiles, the custom maps do not appear. Note, custom maps are downloaded/installed as basemaps, not overlays. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go offline. 
2. Go into Map Layers. 
3. See error: Custom offline map tiles will not appear.

**Expected behavior**
When custom basemap tiles are downloaded, the expected outcome is being able to choose them when offline and freely switch between different custom basemaps. 

**Screenshots**
![StraboIssueScreenshot](https://user-images.githubusercontent.com/80287649/176076056-07a039ae-d292-4231-8ff8-3891552bbbaa.jpg)

**iPad (please complete the following information):**
 - Device: iPad Pro (11inch, 3rd generation)
 - OS: iOS 15.5
 - StraboSpot Version: 1.24.0

**Additional context**

**Comment by NathanNovak** [comment]
@dmongovin this issue has been fixed and will be available in a new release which should go out this week.
