### ISSUE TITLE
KML/KMZ import to StraboSpot2 project

### ISSUE THREAD

**Issue by bwwjohnson** [StraboSpot/StraboSpot2#455]
Hi there! I would like to be able to import field sites previously scouted on the computer in Google Earth or QGIS into a StraboSpot project. I.e. I’d like to import points, lines and polygons as shapefiles or KML/KMZ into a StraboSpot project.

Is this currently possible? If not, will it be possible one day?

Thanks!

**Comment by NathanNovak** [comment]
@bwwjohnson ,
Thanks for your question.  Currently you can load a shapefile into a project through the website ([www.strabospot.org/load_shapefile](https://strabospot.org/load_shapefile)). There have been talks about importing KMZ files in the future, but it is not known when that will be just yet.
