### ISSUE TITLE
notes panel requires saving twice

### ISSUE THREAD

**Issue by eschermer** [StraboSpot/StraboSpot2#457]
**Describe the bug**
When you write a note at a spot and hit save, then a second window pops up asking to save again.  It seems like once should be enough

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes/No
Yes

1. Go to  a spot
2. Click on notes, type in a note
3. hit save
4. see an "unsaved changes" warning box
5. hit save again. 

**Expected behavior**
HIt save once to save the note

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: IPad mini 6
 - OS: [e.g. iOS 15.5
 - StraboSpot Version 1.24

**Additional context**

**Comment by jessicagood** [comment]
Fixed with commit ac8a5fe7621c4bffed30687bf97ef1a44b3aee42
