### ISSUE TITLE
Blank White Screen

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#477]
User dowloaded Testflight version 1.30.1 (4). Since then, the Strabospot app has not loaded properly. When attempting to open it just displays a white screen.

**Comment by jessicagood** [comment]
Try uninstalling the app and then doing a clean install. That worked for @panamint55

**Comment by ellennelson10** [comment]
@NathanNovak When I updated to 1.30.1 (4) on testflight, my app also does not go past a black screen. Redownloading the app store version does bring all my data back.
[RPReplay_Final1666286962.mov.zip](https://github.com/StraboSpot/StraboSpot2/files/9832573/RPReplay_Final1666286962.mov.zip)

**Comment by NathanNovak** [comment]
Did you try uninstalling the pervious app then installing the TF version?

**Comment by ellennelson10** [comment]
@NathanNovak That worked! Can I close this then?

**Comment by NathanNovak** [comment]
Awesome! Yeah go ahead and close this. If it creeps up again we can start a
new issue.
