### ISSUE TITLE
Strat section Page display

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#480]
**Is your feature request related to a problem? Please describe.**
When the Strat settings page is displayed and then an interval is selected the settings go away and leave only the toggle to add a strat section at this spot.

**Describe the solution you'd like**
Should switch to the interval page and show the interval info

**Comment by jessicagood** [comment]
@ellennelson10 or @panamint55 Would anyone ever want to nest one strat section within another? If that's a workflow we want to keep, then this is working how it should be - giving the user has the option to add a strat section to an interval.

**Comment by panamint55** [comment]
How is it working now?

From: Jessica Good ***@***.***>
Reply-To: StraboSpot/StraboSpot2 ***@***.***>
Date: Tuesday, September 26, 2023 at 12:19 PM
To: StraboSpot/StraboSpot2 ***@***.***>
Cc: Doug Walker ***@***.***>, Mention ***@***.***>
Subject: Re: [StraboSpot/StraboSpot2] Strat section Page display (Issue #480)


@ellennelson10<https://github.com/ellennelson10> or @panamint55<https://github.com/panamint55> Would anyone ever want to nest one strat section within another? If that's a workflow we want to keep, then this is working how it should be - giving the user has the option to add a strat section to an interval.

**Comment by jessicagood** [comment]
Fixed with commit fdcc76b
