### ISSUE TITLE
Shortcut Button Issues

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#490]
**Describe the bug**
I found some bugs with the shortcut buttons while testing Android. I then checked, and they are also present on the iPad.
1) Adding a "sketch" spot from shortcut produces "Error Saving Sketch!"
2) If you add two "sample" or "tag" spots in a row the spot number does not increase (These two for sure, I couldn't find it on other ones, but I might have missed them).
3) This one is Android specific, but the note shortcut window gets cut off at the top of the screen.

**To Reproduce**
Yes

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S7 and iPad pro 3rd Generation
 - OS: One Ui Version 3.1/Android Version11 and iOS 16.2
 - StraboSpot Version: 1.35.3 and 1.35.2

**Comment by NathanNovak** [comment]
1. is fixed in commit 67814ff1c5e62fad998a06415f589ce56d616c51
3. is fixed in commit 33ab6526839fdb4e8c20091bf75885f117d60c4b

**Comment by NathanNovak** [comment]
3. is fixed in commit 59f8d1262bfc6bf357e314691a5dc4c44f0732f8
