### ISSUE TITLE
Surface Feature Toggle button doesn't stay on

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#494]
**Describe the bug**
Users are able to turn on "This is a surface feature" for polygonspots, however after saving and returning to the overview page the toggle button stays in the off position.

**To Reproduce**
Draw a polygon. Select "this is a surface feature". Define Surface feature. Save.

**Smartphone (please complete the following information):**
Device: iPad pro 3rd Generation
OS: iOS 16.2
StraboSpot Version: 1.35.2

**Comment by jessicagood** [comment]
fixed with commit https://github.com/StraboSpot/StraboSpot2/commit/d55e08cd226d2a0d26168ff1f8c0f036cfd1292b
