### ISSUE TITLE
Annotating photos crashes app

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#503]
On apple version 1.42.0, when users attempt to annotate photos, the app crashes. See attached video. I was able to reproduce it after redownloading the app, and was told about it by a user that found it on multiple of their iPads.

[RPReplay_Final1685055086.MP4.zip](https://github.com/StraboSpot/StraboSpot2/files/11569977/RPReplay_Final1685055086.MP4.zip)

**Comment by NathanNovak** [comment]
Uploaded a new version (1.42.1) that should fix the Sketching and Annotating crashing issue
