### ISSUE TITLE
Error Getting Map Camera

### ISSUE THREAD

**Issue by bozhang-PhD** [StraboSpot/StraboSpot2#506]
**Describe the bug**
the popup "Error Getting Map Camera" and can not "zoom to GPS",  with the Location permission. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to 'Mai Map View'
2. Click on 'Pan & Zoom to GPS'
3. See error "Error Getting Map Camera" and No available Map in the "May Layers"

**Expected behavior**
Show my location on the Map

**Screenshots**
![2e9a4b1d01ffef168e3adbe7c969fa6](https://github.com/StraboSpot/StraboSpot2/assets/17062534/f5abeb34-2320-4bca-a625-0a743281155a)
![3756d9d25a6fd032a5a8bff6ba1e0db](https://github.com/StraboSpot/StraboSpot2/assets/17062534/404c01aa-2f9e-42bc-8139-53aa13f4f55c)

**Smartphone (please complete the following information):**
 - Device: [iPad mini6] 
 - OS: [e.g. iPadOS 16.5]
 - StraboSpot Version [1.42.1]

**Comment by NathanNovak** [comment]
@bozhang-PhD are you connected to an access point?  It doesn't look like you have any maps saved to view offline.
