### ISSUE TITLE
Strong (Simple?) Request: Separate options for "Clear" and "Undo" for sketching

### ISSUE THREAD

**Issue by dmongovin** [StraboSpot/StraboSpot2#510]
**Is your feature request related to a problem? Please describe.**
The sketching option under images in StraboSpot2 is very valuable, and I utilize it often (especially when teaching!). However, I can't count how many times I've accidentally "Cleared" a sketch I've spent a lot of time on instead of "Undo"ing my previous pen-line.

**Describe the solution you'd like**
 I think a simple fix for this would to be move the "Clear" option to the other side, or separate from all other options completely. 

![IMG_0103](https://github.com/StraboSpot/strabo-mobile/assets/80287649/3dfd98f2-3aa0-4e6a-9bee-ba37489ad05f)

**Comment by NathanNovak** [comment]
@dmongovin I made the change and moved the Clear button to the other side.  We cannot do to much modification since this sketch package is a imported package.  Hope this helps.
