### ISSUE TITLE
Igneous rocks and Metamorphic rocks not uploading to server

### ISSUE THREAD

**Issue by srmulcahy** [StraboSpot/StraboSpot2#511]
**Describe the bug**
Used StraboSpot2 on an iPad and used the Igneous and Metamorphic rock options for rock descriptions. After completing work in the field and uploading the project to the server, none of the rock description data is on the server and it is not included in the downloaded files (Field Notebook, XLS, etc.). We also used sedimentary rock descrition and that data uploaded just fine - it's present on the server and included in the pdf of downloaded Field Notebook. 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes
Five students working on different tablets all have the same results.

1. Create a new spot
2. Add and igneous rock (or metamorphic rock)
3. Complete all of the data entry
4. Upload project to StraboSpot
5. Igneous and Metamorphic rock descriptions do not appear online or in any downoalds

**Expected behavior**
Expect the data to appear online and in the downloads.

**Smartphone (please complete the following information):**
 - Device: iPAd mini 5th gen
 - OS: 15.5 and 15.6
 - StraboSpot2 Version 1.42.1

**Comment by jessicagood** [comment]
@srmulcahy The online viewer is still using StraboSpot 1 while you entered the data from the app in StraboSpot 2. Unfortunately (or fortunately depending on your viewpoint) for the particular data you are are looking at there was a change in the data structure between StraboSpot 1 and StraboSpot 2 (the app). In StraboSpot 1 a user could only enter one Ig/Met rock per spot but StraboSpot 2 was modified so the user could enter multiple Ig/Met rocks in a spot. Data from StraboSpot 2 is not backwards compatible to StraboSpot 1 (though the reverse works). We are currently working on a new online viewer for StraboSpot 2.

Can you confirm that you are able to to see your Ig/Met data if you download your project to a different device running StraboSpot 2? Or redownload it on the same device with StraboSpot 2? The Ig/Met data uploads and redownloads fine for me as long as I am on StraboSpot 2.

In terms of downloading from the website, which type of download are you trying to use @srmulcahy? I don't see the Ig/Met data in the Shapefile or Field Book downloads. I'll loop @jasonash into this conversation.

**Comment by srmulcahy** [comment]
I can confirm that the igmet data is present when we download projects to
different devices for the same device.

We've been downloading the field books as part of a class exercise and we
do not see the Ig/Met descriptions in the PDF of the field book

**Comment by jasonash** [comment]
The export options at strabospot.org will need to be altered to accommodate the new ig/met data structure. I will make these changes when I return to the office next week.

**Comment by jasonash** [comment]
Petrology information has been fixed for the FieldBook output at strabospot.org. I will work towards fixing the output for xls and shapefile export now.

**Comment by srmulcahy** [comment]
I can confirm that the petrology information appears in the FielBook pdf
output. Thank you!
