### ISSUE TITLE
Add 3D structure adding plane and line orientations not working

### ISSUE THREAD

**Issue by srmulcahy** [StraboSpot/StraboSpot2#512]
**Describe the bug**
When using Add a 3D structure and working to measure Hinge Orienation, Axial Surface Orientation, Foliation Associated with Fold , when you click on the Tap to Measure, the data does not appear in the spot. If you try Switch to Manual Input the program closes upon pressing Add to Attribute.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to 3D structures
2. Click on Hine Line Orientation, Axial Surface Orientation, or Foliation associated with Fold
3. Tap to Measure
4. Hear the clicking sound of the measurement
5. No data is recorded
6. Click Switch to Manual
7. Enter trend and plunge
8. Click Add to Attribute
9. Program closes

**Expected behavior**
I would expect the fold observations to appear in the spot.

**Smartphone (please complete the following information):**
 - Device: iPad mini 5th
 - OS: 15.5
 - StraboSpot2 Version [e.g. 1.42.1]

**Additional context**

**Comment by NathanNovak** [comment]
Hi @srmulcahy. Thanks for letting us know! I fixed the bug and will be in the next release.
