### ISSUE TITLE
Editing Spot and Vertices location crashes app

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#517]
On both Android and iOS editing the location of a spot or a vertex crashes the application.  Was able to recreate this after starting the app on both devices.

Version 1.46.2 on a Android Galaxy Tab Tab S7 and an iPad Pro 3rd Generation

[RPReplay_Final1695265268.mov.zip](https://github.com/StraboSpot/StraboSpot2/files/12685548/RPReplay_Final1695265268.mov.zip)

**Comment by NathanNovak** [comment]
fixed with commit 30704635a22e43e58af9adaed9835b51d924b970
