### ISSUE TITLE
Shortcut Buttons not working

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#519]
Turned on shortcuts in the Preferences menu.  The Photo and Sketch shortcuts do not do anything when pressed.  The other shortcut buttons bring up the QEM, and users are able to enter the data and press save data, but a new spot is not created and the user cannot see where the data goes.  If I add another spot manually, the number succesion continues like the shortcut spots are not made at all.

Version 1.46.2 on a Android Galaxy Tab Tab S7

**Comment by jessicagood** [comment]
Fixed with commit 465e8f8d180f37c889ffd1a063341c056c1aedcc
