### ISSUE TITLE
Small Screen Sample QEM 

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#523]
In the Sample QEM on small screens the "Inplaceness of Sample" is obscured by the Oriented/Unoriented boxes. Can still move the slider, but it is unreadable.

On an iPhone running iOS 17.1.2.
StraboSpot version 2.0.0

![IMG_0309](https://github.com/StraboSpot/StraboSpot2/assets/91563766/a661055c-35d6-4c8b-a921-79fb7f6c42a0)

**Comment by jessicagood** [comment]
Fixed with commit 7729a98
