### ISSUE TITLE
Sketch shortcut does not work in Small Screens

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#524]
When creating a spot using the sketch shortcut button, a new spot is created and the notebook opens. However, the sketch tool does not open as it should.

On an iPhone running iOS 17.1.2.
StraboSpot version 2.0.0

**Comment by jessicagood** [comment]
Fixed with commit 465e8f8d180f37c889ffd1a063341c056c1aedcc
