### ISSUE TITLE
Long QEMs go off the screen

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#525]
On StraboSpot version 2.0.0 on iPad and Android, long QEM (e.g., Geologic unit, Measurement, Sedimentary rock types, metamorphic rock, add interval) go off the screen in horizontal orientation.  Users are then unable to close the QEM or save/add interval in some cases.

![IMG_2322](https://github.com/StraboSpot/StraboSpot2/assets/91563766/eacc9ee5-a9b5-440f-b9cb-06e740358592)

**Comment by NathanNovak** [comment]
fixed with commits bca73b2f28081986fbfcda1422163b31bc0c7b21, 608f143fb1c317bd17c3aa163f27e6080a9b1d6c, aecfa620e180c59a23ae1e70acb7de1fd3a99f4b, cc9d04a3e6dbd0c7a01c6337dee12f4fe34728d9
