### ISSUE TITLE
Error! Success!

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#526]
On StraboSpot version 2.0.0 on iPad after lassoing spots for Stereonet, the pop up window says "Error! Success! Data has been copied to the clipboard".
Shouldn't say error if the lassoing worked.

![IMG_2318](https://github.com/StraboSpot/StraboSpot2/assets/91563766/8a8db4f8-741d-4b86-a098-76f2a76b3cdb)

**Comment by NathanNovak** [comment]
fixed with commit 2ceadbb3dded0de51ec5687376bc50f83b5af1ef
