### ISSUE TITLE
Map Symbol window

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#527]
On StraboSpot version 2.0.0 on iPad the map symbol window goes below the screen if the user has a lot of different symbol types.

![IMG_2321](https://github.com/StraboSpot/StraboSpot2/assets/91563766/7e957803-f4a2-4d7f-9451-4f2d8c5e1949)

**Comment by NathanNovak** [comment]
fixed with commit bca73b2f28081986fbfcda1422163b31bc0c7b21
