### ISSUE TITLE
Adding spots in Android not working properly 

### ISSUE THREAD

**Issue by ellennelson10** [StraboSpot/StraboSpot2#528]
In StraboSpot 2.0.0 on a Galaxy Tab S7 adding spots to a map is not working properly. 

1) When users add a spot it opens up the recent spots not the notebook.
2) When trying to add a point spot, it always adds it behind the point spot button. When adding a line or polygon the first vertice is always added behind the line or polygon button respectively.

**Comment by jessicagood** [comment]
Fixed with commit [02a2b01](https://github.com/StraboSpot/StraboSpot2/commit/02a2b01a50e55192f9fc5c51920fe8b2f4efb9b6).

A View with absolute position nested in an Animated view with absolute position was causing icon presses to trigger a map press. Only on Android. iOS and web not affected.
