### ISSUE TITLE
Incorrect value highlighted when adding Igneous Volcanic Rock

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#531]
**Describe the bug**
When pressing the "+" to add a volcanic rock the modal s Plutonic selected but shows the values for volcanic.

**Comment by jessicagood** [comment]
Fixed with commit [72da6c5](https://github.com/StraboSpot/StraboSpot2/commit/72da6c5e69ca6e1efd1b8999ebd21651600619e0)
