### ISSUE TITLE
Selecting Planar type is not intuitive

### ISSUE THREAD

**Issue by andrewkrh** [StraboSpot/StraboSpot2#534]
**Is your feature request related to a problem? Please describe.**

In the compass tool users should select a planar type prior to taking a measurement, but it is not clear that the "Planar Feature Type" box is a button. New users do not intuitively understand how to define the measurement type

**Describe the solution you'd like**
The "Planar Feature Type" box within the compass tool could have a bezel or some other border to indicate that it is a button

**Describe alternatives you've considered**
Planar Feature Type selection in the compass tool could be a drop-down menu

**Additional context**
Same issue for "Linear Feature Type"

Version 2.1.2

**Comment by NathanNovak** [comment]
Hi @andrewkrh,

I attached a video of the compass whil changing between the different types of measurements.  The button bar on the top highlights which type of measurement is currently selected in the version of the app you are running.  If I am missing something please let me know.

[RPReplay_Final1705954107.mov.zip](https://github.com/StraboSpot/StraboSpot2/files/14014964/RPReplay_Final1705954107.mov.zip)

**Comment by andrewkrh** [comment]
Hi Nathan,

The issue in not the top button bar, but rather the Label selection, where users select what kind of planar feature they are measuring (bedding, foliation, fracture, etc.). I worked with several new users a couple weeks ago and they struggled to understand what I was trying to tell them to do. Between having to scroll down (on iPhone version) to select a planar feature type and there not being a visual cue that there is a button, most students did not understand how to use the tool intuitively. 

This is more of an issue of easy of use for introductory users, namely students, not something that is keeping the tool from functioning as intended. My personal preference is to use templates, but that can take some investment for new users. 

Thanks,
Andrew
