### ISSUE TITLE
Crash while installing custom map

### ISSUE THREAD

**Issue by jscaine** [StraboSpot/StraboSpot2#547]
**Describe the bug**
I was uploading a custom map from a .zip file obtained from USGS NGMDB and tried to switch it from an overlay to an off-line available map.  I commonly forget the steps to get the custom map only then save it's tiles.  But, eventually I was able to get the tile  save prompt and when I clicked it the program froze.  I had to eventually delete it from my iPad and reinstall.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
No.  I did not try a new project.  But, I tried the process again in an earlier version of SS2 and it worked.

**Expected behavior**
No crashing.

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: iPad Mini 5
 - OS: Latest iOS
 - StraboSpot Version: The version before the last TestFlight push.  I will try to get better info on these questions if this happens again.

**Additional context**

**Comment by NathanNovak** [comment]
Fixed with commit ad1e12e1cb73ee381320501265e20209e242a3dc

**Comment by jscaine** [comment]
[like]  Caine, Jonathan S reacted to your message:
________________________________
From: Nathan Novak ***@***.***>
Sent: Friday, April 19, 2024 10:26:02 PM
To: StraboSpot/StraboSpot2 ***@***.***>
Cc: Caine, Jonathan S ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [StraboSpot/StraboSpot2] Crash while installing custom map (Issue #547)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Fixed with commit ad1e12e<https://github.com/StraboSpot/StraboSpot2/commit/ad1e12e1cb73ee381320501265e20209e242a3dc>

**Comment by jscaine** [comment]
[like]  Caine, Jonathan S reacted to your message:
________________________________
From: Nathan Novak ***@***.***>
Sent: Friday, April 19, 2024 10:26:02 PM
To: StraboSpot/StraboSpot2 ***@***.***>
Cc: Caine, Jonathan S ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [StraboSpot/StraboSpot2] Crash while installing custom map (Issue #547)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Closed #547<https://github.com/StraboSpot/StraboSpot2/issues/547> as completed.
