### ISSUE TITLE
When Loading Projects From Device, Updated always says "Invalid Date"

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot2#555]
When Loading Projects From Device, Updated always says "Invalid Date"

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Download a project from the server or simply create a new project.
2. Save project do device.
3. Go to My StraboSpot -> Projects from Device

**Expected behavior**
"Invalid Date" will always appear below export name.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iPadOS 17.4.1
 - StraboSpot Version StraboSpot2 v2.4.3

**Additional context**

**Comment by jessicagood** [comment]
Fixed with commit 21e90426c6be3d8261c8ebdfcbad6215794b3a14

For importing, the last modified date isn't actually known until the project file is opened so just remove this line if there is not a valid date.

**Comment by jasonash** [comment]
Thanks.
