### ISSUE TITLE
Option to forbid duplicate spot or sample names

### ISSUE THREAD

**Issue by mwloewen** [StraboSpot/StraboSpot2#560]
With the way we have used StraboSpot, a "spot" and a "sample" are a unique observation. We would never want to have duplicate spot names, and certainly not duplicate sample names (although a sample can share it's parent spot name). Returning from the field with two samples with the same name would be a critical error, possibly rendering both samples garbage unless the identity could be determined form the sample description. Similarly, identical spot names for two different observations can be problematic ("Tags" we've learned is a great way to note the same thing in multiple places). 

I can see how some might use the app in a way where they WANT duplicate spot names, while I would prefer to forbid it.

Could the app at least warn you that you are creating a spot or sample with a duplicate name? Or could the app have a toggle option of water to allow duplicate names at all? 

Thank you for considering this!

**Comment by jessicagood** [comment]
Added optional warnings for spot names and sample names with commits 0abc7a66706cd509038bff85831b6786ebc43a6d and 395816d6550bb8a804ca5e18abed8485e1c92a99

**Comment by mwloewen** [comment]
Lovely! Works really well in test version. One suggestion: The popup warning lasts less than 2 seconds and would be easy to miss. If someone turns this option on presumably they really don't' want to accidentally make duplicate spot names. I'd suggest keeping the warning up longer, or even have a popup that requires acknowledgement ("Are you sure you want to do this? yes-no")

**Comment by jessicagood** [comment]
Doubled the toast warning to a duration of 3 seconds with commit e2315c1401cc5d82bb36bc1a28f799e7cb4ca2c3. I can easily change this again to make it longer. But you won't see this change until a new version is released.

Requiring an acknowledgement is a mess of development work, hence the toast for now.
