### ISSUE TITLE
Need Layer Added to StraboSpot2 Map Interface

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot2#562]
We need to add a new layer to the StraboSpot2 Map Interface:

Layer name: USGS Hillshade

Attribution: The USGS 3D Elevation Program (3DEP) Bare Earth DEM Dynamic Service
Attribution URL: https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer

Example tile URL: https://tiles.strabospot.org/v5/usgs.hillshade/13/1668/3134.png

Maximum Zoom Level: 19

**Comment by jessicagood** [comment]
Added with commit [87add9b](https://github.com/StraboSpot/StraboSpot2/commit/87add9bfa20f6cd94789c6fd963538ebc52ce310)
