### ISSUE TITLE
Unable to Create Spots After Downloading Empty Dataset

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot2#565]
**Describe the bug:**
Unable to Create Spots After Downloading Empty Dataset

**To Reproduce:**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

**Steps to reproduce the behavior:**

1. On your mobile device, create a new project.
2. Create a point spot anywhere on the map in the default dataset.
3. Create a new dataset named “test” but don’t switch it on or make it default.
4. Upload project to StraboSpot.
5. Create a new project on your mobile device, just to clear out data.
6. Download original project from StraboSpot.
7. When the original project is downloaded, the “test” dataset will be active.
8. If you try to create a spot in the “test” dataset, it will fail.
9. You can switch back to the “default” dataset, and you can add spots.
10. If you switch back to the “test” dataset, spots cannot be placed.

**Expected behavior:**
Unable to place spots in any empty dataset downloaded or restored.

**Screenshots:**
N/A

**Smartphone (please complete the following information):**
 - iPad Pro (11-inch)
 - OS: iPadOS 17.5.1
 - StraboSpot Version StraboSpot2 v2.5.4

**Additional context:**
This issue was reported by Noah Phillips. He should be contacted with a resolution: nphilli2@lakeheadu.ca

**Comment by mwloewen** [comment]
I also have this issue, posted #572 before I saw it was posted here!

**Comment by jessicagood** [comment]
Fixed with commit 548dd881532999ffff8ae6bf297d8eb6731af661
