### ISSUE TITLE
Custom Maps as Overlays Disappear When Reloading App

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot2#568]
**Describe the bug:**
Custom Maps as Overlays Disappear When Reloading App

**To Reproduce:**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

**Steps to reproduce the behavior:**

1. Add a custom map to project and set it to "Display as overlay."
2. Turn on overlay. It should appear as expected.
3. Close StraboSpot2 on your mobile device.
4. Re-open StraboSpot2.
5. Overlay does not appear. Toggling the layer on and off in Map Layers toolbar does nothing.
6. Go to custom map's settings and turn off "Display as overlay."
7. Click "Update."
8. Go to custom map's settings again, and turn on "Display as overlay."
9. Toggling on layer should now work again.
10. Closing the app will result in layer disappearing again.

**Expected behavior:**
Overlays should persist between app restarts.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPad Pro (11-inch)
 - OS: iPadOS 17.5.1
 - StraboSpot Version 2.5.3

**Additional context:**
This bug was reported by Nicole Moore (Nicole.Moore@pomona.edu). She should be updated on the status of this fix.

**Comment by NathanNovak** [comment]
Fixed with commit 
fac76a9
