### ISSUE TITLE
When Adding Custom Map, Modal Appears that Cannot be Closed

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot2#570]
**Describe the bug**
When adding a custom map, a modal appears at the end of the process that cannot be closed. The modal says, "Status Success! Map has been added or updated"...

**To Reproduce**
Yes

Add a new custom map. Give it a name. I used StraboSpot My Maps with id 5ced49be11423
Click Save
The success modal appears and cannot be closed. Clicking on the modal or outside of the modal has no effect.

**Expected behavior**
There should be a way to close the modal.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11"
 - OS: iPadOS 17.5.1
 - StraboSpot Version 2.5.2

**Additional context**

**Comment by NathanNovak** [comment]
fixed with commit 1177325974bddeea9558cd38f5c1882dec03b5a3
