### ISSUE TITLE
naming convention options unexpectedly revert to default

### ISSUE THREAD

**Issue by mwloewen** [StraboSpot/StraboSpot2#571]
**Describe the bug**
The new spot naming convention options (thank you!) work as expected until a second spot is placed on an image basemap. When the second spot is created, all spot  and sample prefix options seem to revert to default values (numeric). 

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Change spot prefix options (ex: Spot prefix = 24ML, Starting number = 1, use map spot as prefix for spots placed on image basemap, restart numbering
2. Add map spot, add spot on image basemap--performs as expected. Add second spot on image basemap, name is just a number and the naming conventions have reverted!

**Expected behavior**
The second spot on the image should sequentially increase in number

**Smartphone (please complete the following information):**
 - Device: ipad mini (note the naming conventions for image basemaps are not available on an iphone!)
 - OS: can check tomorrow
 - StraboSpot Version current

**Comment by jessicagood** [comment]
Good catch! Fixed with commit 786903c12d0e0e1e52eb1f2a5148c5beeae00773
