### ISSUE TITLE
unable to place spot in empty dataset

### ISSUE THREAD

**Issue by mwloewen** [StraboSpot/StraboSpot2#572]
**Describe the bug**
When starting a new project with empty datasets (created online), the place spot button shows a cursor but dosen't make the spot, but the naming convention does _think_ it added a spot and start advancing spot numbers each time you click.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes, and on different devices

1. New project, create empty datasets on the online app.
2. Make one of the empty datasets the active dataset
3. Try to place a spot---nothing happens!
4. If I go to a dataset that has spots, make a spot in it, I can now make spots in the empty datasets when I go back and activate them, weird!

**Expected behavior**
When I use the place spot icon it should place a spot in the active dataset, even if its empty.

**Smartphone (please complete the following information):**
 - Device: iPhone11, iPad Mini
 - OS: iOS17.5.1, ipad mini unknown
 - StraboSpot Version:2.5.2

**Additional context**
Found  work-around, but it's awkward.

**Comment by jessicagood** [comment]
Fixed with commit 548dd881532999ffff8ae6bf297d8eb6731af661
