### ISSUE TITLE
Attempting to Change Path in Custom Endpoint Causes Strabo2 to Crash

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot2#578]
**Describe the bug**
When attempting to change the value (/db) in the path of the custom database endpoint, the Strabo2 app crashes.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to Miscellaneous and try changing the path in the custom endpoint section.

**Expected behavior**
Should be able to change endpoint.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11"
 - OS: iPadOS v17.5.1
 - StraboSpot Version: Tested with 2.5.2 and 2.6.0

**Additional context**

**Comment by NathanNovak** [comment]
We fixed this with commit 42196cf9a8d31ac8ee0b369aec32c71bea0733a1
