### ISSUE TITLE
Adding samples to a spot not working

### ISSUE THREAD

**Issue by mwloewen** [StraboSpot/StraboSpot2#582]
**Describe the bug**

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Make a spot, add a sample and description, "save sample". 
2. Close pop-up sample dialog
3.  "Unsaved Changes prompt" choose "yes"
4.  Look at list of samples, the sample we tried to save has advanced one step in the auto sample naming convention (what was an "a" is now a "b"). The description has been deleted.

**Expected behavior**
The sample ID should not change (still "a") and the description should not be deleted.

**Smartphone (please complete the following information):**
 - Device: [ipad mini 5th generation]
 - OS: [ios 17.5.1]
 - StraboSpot Version [2.7.1]

**Additional context**
Using testflight version, using test mode, using naming conventions (for samples, turned on "prepend spot name" and "append letter instead of number"

**Comment by jessicagood** [comment]
Ok, I see it now. I will work on fix for this but there are a few ways around this:
1) Actually just hit "Save" instead of trying to close the modal without saving changes
2) Hit "No" instead of "Yes" for Unsaved Changes if prompted

**Comment by jessicagood** [comment]
Fixed with commit e43a9d9
