### ISSUE TITLE
Update Spots in Map Extent Bug

### ISSUE THREAD

**Issue by jessicagood** [StraboSpot/StraboSpot2#598]
The first time the app is loaded the Update Spots in Map Extent button in the Spots List doesn't return anything, even if there are spots in the map extent. `spotsSelected` and `spotsNotSelected` are empty, even if they were just set with values. The button works again after a spot is selected, or after the map action, zoom to extent of spots is run or even just if the basemap is changed.

**Comment by NathanNovak** [comment]
Fixed in commit eee8006aa41d2b93a051578dc3b845682cf500b2
