### ISSUE TITLE
Unable to Add Custom Map via StraboSpot Web Interface

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/StraboSpot2#599]
**Describe the bug**
When trying to add a custom map using the StraboSpot web interface, the attempt fails with this error:

<img width="336" alt="Screenshot 2024-09-04 at 4 49 32 PM" src="https://github.com/user-attachments/assets/a1df3ebe-e4a2-40a2-90fc-b1f70abf0d6d">

This issue was reported by Michael Frothingham @ USGS (mfrothingham@usgs.gov)

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Try to add custom map using the web interface

**Expected behavior**
Map should be added

**Screenshots**
See above

**MacBook Pro - Firefox Browser:**
    StraboSpot Version 2.8.0

**Comment by NathanNovak** [comment]
Fixed with commit 
c9595d2
