### ISSUE TITLE
Inability to deselect geologic unit tags

### ISSUE THREAD

**Issue by raedotcom** [StraboSpot/StraboSpot2#610]
**Describe the bug**
Geologic unit tags cannot be deselected from a point once they are added. I will reassign the existing tag or deselect it entirely and upload the project, but the old tag remains on the spot if it has been deselected, or it now will have 2 tags (new and old) if it has been reassigned.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Find point with existing tag
2. Click into the tag tab of the point to reassign
3. Scroll to currently selected geologic unit tag
4. Deselect tag
5. Save project to server
6. Open project and find the spot you just edited and its associated tags

**Expected behavior**
Deselected tag will remain on edited point.

**Additional context**
Our project has a few dozen geologic unit tags, over 15 basemaps, about 200 points, and some lines plotted. Maybe this bug is due to the size of the project.

**Comment by jessicagood** [comment]
Thanks for the detailed steps. This helped us recreate the problem and it has now been fixed by @jasonash. Please give it a try again and respond here it works for you now. Then this issue can be closed.
