### ISSUE TITLE
Add details to Macrostrat base map

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#624]
<div type='discussions-op-text'>

<sup>Originally posted by **alexanderlusk** January 28, 2021</sup>
On the macrostrat website, details are provided for each unit (name, age, description, etc.). Can this information be added to the macrostrat layer in strabo?</div>

**Comment by jessicagood** [comment]
Added with commits aa2186451c816445e30913ae841a66abc8282326 and b10d2db60d35b85d0498cdee464d9f809f2beb11
